# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'DUZB_XMJ' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
pod 'Alamofire', '~> 4.2.0'
pod 'Kingfisher', '~> 3.2.4'
  # Pods for DUZB_XMJ

end
